"""
Workflow Generation Database Models

Defines database tables for workflow templates, generated workflows,
workflow executions, and workflow patterns.
"""
from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey, Float
from sqlalchemy.types import JSON, Enum
from sqlalchemy.orm import relationship
import enum

from app.models.base import BaseModel


class WorkflowStatus(enum.Enum):
    """Status of generated workflow"""
    DRAFT = "draft"
    ACTIVE = "active"
    ARCHIVED = "archived"


class ExecutionStatus(enum.Enum):
    """Status of workflow execution"""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class WorkflowCategory(enum.Enum):
    """Categories for workflow templates"""
    DATA_PROCESSING = "data_processing"
    API_INTEGRATION = "api_integration"
    AUTOMATION = "automation"
    ETL = "etl"
    MACHINE_LEARNING = "machine_learning"
    DOCUMENT_PROCESSING = "document_processing"
    NOTIFICATION = "notification"
    SCHEDULING = "scheduling"
    CUSTOM = "custom"


class WorkflowGenerationTemplate(BaseModel):
    """
    Template definitions for workflow generation.
    
    Stores reusable workflow templates that can be used to generate
    specific workflows with custom parameters.
    """
    __tablename__ = "workflow_generation_templates"
    
    # Basic information
    name = Column(String(100), nullable=False, index=True)
    description = Column(Text, nullable=True)
    category = Column(
        Enum(WorkflowCategory),
        default=WorkflowCategory.CUSTOM,
        nullable=False
    )
    
    # Template definition
    template_schema = Column(JSON, nullable=False)  # Workflow structure definition
    parameters = Column(JSON, nullable=True)  # Input parameters schema
    
    # Access control
    is_public = Column(Boolean, default=False, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    
    def __repr__(self):
        return f"<WorkflowGenerationTemplate(id={self.id}, name='{self.name}', category='{self.category}')>"


class GeneratedWorkflow(BaseModel):
    """
    AI-generated workflows from templates or natural language descriptions.
    
    Stores the actual workflows generated by the AI engine.
    """
    __tablename__ = "workflow_generated_workflows"
    
    # Template reference
    template_id = Column(Integer, ForeignKey("workflow_generation_templates.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    
    # Workflow identification
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    
    # Generated workflow structure
    workflow_schema = Column(JSON, nullable=False)  # Generated workflow structure
    generation_params = Column(JSON, nullable=True)  # Parameters used for generation
    
    # Status
    status = Column(
        Enum(WorkflowStatus),
        default=WorkflowStatus.DRAFT,
        nullable=False
    )
    
    # Relationships
    template = relationship("WorkflowGenerationTemplate", back_populates="generated_workflows")
    executions = relationship(
        "WorkflowGenerationExecution",
        back_populates="generated_workflow",
        cascade="all, delete-orphan"
    )
    
    def __repr__(self):
        return f"<GeneratedWorkflow(id={self.id}, name='{self.name}', status='{self.status}')>"


class WorkflowGenerationExecution(BaseModel):
    """
    Execution tracking for generated workflows.
    
    Records each execution of a workflow, including input data,
    output data, execution time, and any errors.
    """
    __tablename__ = "workflow_generation_executions"
    
    # Workflow reference
    generated_workflow_id = Column(
        Integer,
        ForeignKey("workflow_generated_workflows.id"),
        nullable=False,
        index=True
    )
    
    # Execution status
    status = Column(
        Enum(ExecutionStatus),
        default=ExecutionStatus.PENDING,
        nullable=False
    )
    
    # Execution data
    input_data = Column(JSON, nullable=True)
    output_data = Column(JSON, nullable=True)
    
    # Performance metrics
    execution_time_ms = Column(Float, nullable=True)
    
    # Error tracking
    error_message = Column(Text, nullable=True)
    
    # Relationships
    generated_workflow = relationship("GeneratedWorkflow", back_populates="executions")
    
    def __repr__(self):
        return f"<WorkflowGenerationExecution(id={self.id}, workflow_id={self.generated_workflow_id}, status='{self.status}')>"


class WorkflowPattern(BaseModel):
    """
    Recognized workflow patterns.
    
    Stores common workflow patterns identified from successful workflow
    executions, with usage statistics for recommendations.
    """
    __tablename__ = "workflow_generation_patterns"
    
    # Pattern identification
    name = Column(String(100), nullable=False, index=True)
    description = Column(Text, nullable=True)
    
    # Pattern definition
    pattern_schema = Column(JSON, nullable=False)  # Pattern structure
    
    # Statistics
    usage_count = Column(Integer, default=0, nullable=False)
    success_rate = Column(Float, default=0.0, nullable=False)  # 0.0 to 1.0
    
    def __repr__(self):
        return f"<WorkflowPattern(id={self.id}, name='{self.name}', usage_count={self.usage_count})>"


# Add relationships to WorkflowGenerationTemplate
WorkflowGenerationTemplate.generated_workflows = relationship(
    "GeneratedWorkflow",
    back_populates="template",
    cascade="all, delete-orphan"
)
